version: '2.2'
services:

  annotate:
    build: .
    image: dojomodeling/annotate:dev
    container_name: annotate
    volumes:
        - ./:/annotate
    ports:
      - 8001:8000
      - 3001:3001
    expose:
      - "8001"
      - "3001"
    networks:
      - annotate
    depends_on:
      - redis
      - processor
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000

  redis:
    container_name: redis-annotate
    image: redis
    ports:
      - 6382:6379
    networks:
      - annotate

  processor:
    build: .
    image: dojomodeling/annotate:dev
    container_name: annotate-processor
    volumes:
      - ./:/annotate
    networks:
      - annotate
    command:
      - python3
      - manage.py
      - rqworker
      - default

networks:
  annotate:
    driver: bridge      
