version: '2.2'
services:

  templater:
    build: .
    container_name: templater
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DOJO_HOST: http://DOJO_URL_HERE:8000
      FLASK_ENV: development
      TEMPLATER_S3_BUCKET: ${TEMPLATER_S3_BUCKET}
    volumes:
      - ./:/templater
    ports:
      - 5000:80
    expose:
      - "5000"
