name: Build

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: [ '15' ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Npm Install
        working-directory: ./ui
        run: npm i

      - name: Lint
        run: make fmt

      - name: Build Containers
        run: make docker_build
