version: "3"
services:
  terminal:
    build: .
    container_name: terminal
    command: -debug -trace -pull-images=false
    ports:
      - 3000:3000
    env_file:
      - .dockerenv
    volumes:
      - ${PWD}/api/server/settings.yaml:/home/app/connector/settings.yaml

