version: "3"
services:

  ui:
    image: dojo-modeling/dojo-ui:dev
    container_name: dojo-ui
    ports:
      - 8080:80
    environment:
      API_HOST: ${PRIVATE_IP}
      WEBSOCKET_HOST: ${PRIVATE_IP}


