version: '2.2'
services:
  api:
    build: .
    container_name: dojo-api
    ports:
      - 8000:80
    expose:
      - "8000"
    env_file:
      - .env  
    networks:
      - dojo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dojo_esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - dojo

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - dojo

  redis:
    container_name: redis1
    image: redis
    ports:
      - 6379:6379
    networks:
      - dojo


volumes:
  dojo_esdata:
    driver: local


networks:
  dojo:
    driver: bridge
